// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: content/closed_vector.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DesignModel.ContentTypes {

  /// <summary>Holder for reflection information generated from content/closed_vector.proto</summary>
  public static partial class ClosedVectorReflection {

    #region Descriptor
    /// <summary>File descriptor for content/closed_vector.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ClosedVectorReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Chtjb250ZW50L2Nsb3NlZF92ZWN0b3IucHJvdG8SDmRlc2lnbi5jb250ZW50",
            "Gi1jb250ZW50L2NvbnRyb2xzL2Nsb3NlZF92ZWN0b3JfY29udHJvbHMucHJv",
            "dG8aF2FwcGVhcmFuY2Uvc3Ryb2tlLnByb3RvGhVhcHBlYXJhbmNlL2ZpbGwu",
            "cHJvdG8irwEKDENsb3NlZFZlY3RvchJNChZjbG9zZWRfdmVjdG9yX2NvbnRy",
            "b2xzGAEgASgLMi0uZGVzaWduLmNvbnRlbnQuY29udHJvbHMuQ2xvc2VkVmVj",
            "dG9yQ29udHJvbHMSJQoEZmlsbBgCIAEoCzIXLmRlc2lnbi5hcHBlYXJhbmNl",
            "LkZpbGwSKQoGc3Ryb2tlGAMgASgLMhkuZGVzaWduLmFwcGVhcmFuY2UuU3Ry",
            "b2tlQhuqAhhEZXNpZ25Nb2RlbC5Db250ZW50VHlwZXNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DesignModel.ContentTypes.Controls.ClosedVectorControlsReflection.Descriptor, global::DesignModel.AppearanceTypes.StrokeReflection.Descriptor, global::DesignModel.AppearanceTypes.FillReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DesignModel.ContentTypes.ClosedVector), global::DesignModel.ContentTypes.ClosedVector.Parser, new[]{ "ClosedVectorControls", "Fill", "Stroke" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ClosedVector : pb::IMessage<ClosedVector>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<ClosedVector> _parser = new pb::MessageParser<ClosedVector>(() => new ClosedVector());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ClosedVector> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DesignModel.ContentTypes.ClosedVectorReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClosedVector() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClosedVector(ClosedVector other) : this() {
      closedVectorControls_ = other.closedVectorControls_ != null ? other.closedVectorControls_.Clone() : null;
      fill_ = other.fill_ != null ? other.fill_.Clone() : null;
      stroke_ = other.stroke_ != null ? other.stroke_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ClosedVector Clone() {
      return new ClosedVector(this);
    }

    /// <summary>Field number for the "closed_vector_controls" field.</summary>
    public const int ClosedVectorControlsFieldNumber = 1;
    private global::DesignModel.ContentTypes.Controls.ClosedVectorControls closedVectorControls_;
    /// <summary>
    /// Contains closed vector's control points.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DesignModel.ContentTypes.Controls.ClosedVectorControls ClosedVectorControls {
      get { return closedVectorControls_; }
      set {
        closedVectorControls_ = value;
      }
    }

    /// <summary>Field number for the "fill" field.</summary>
    public const int FillFieldNumber = 2;
    private global::DesignModel.AppearanceTypes.Fill fill_;
    /// <summary>
    /// Defines the filling of the inner area of a closed vector.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DesignModel.AppearanceTypes.Fill Fill {
      get { return fill_; }
      set {
        fill_ = value;
      }
    }

    /// <summary>Field number for the "stroke" field.</summary>
    public const int StrokeFieldNumber = 3;
    private global::DesignModel.AppearanceTypes.Stroke stroke_;
    /// <summary>
    /// Defines closed vector outline appearance.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DesignModel.AppearanceTypes.Stroke Stroke {
      get { return stroke_; }
      set {
        stroke_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ClosedVector);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ClosedVector other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ClosedVectorControls, other.ClosedVectorControls)) return false;
      if (!object.Equals(Fill, other.Fill)) return false;
      if (!object.Equals(Stroke, other.Stroke)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (closedVectorControls_ != null) hash ^= ClosedVectorControls.GetHashCode();
      if (fill_ != null) hash ^= Fill.GetHashCode();
      if (stroke_ != null) hash ^= Stroke.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (closedVectorControls_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ClosedVectorControls);
      }
      if (fill_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Fill);
      }
      if (stroke_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Stroke);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (closedVectorControls_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ClosedVectorControls);
      }
      if (fill_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Fill);
      }
      if (stroke_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Stroke);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (closedVectorControls_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClosedVectorControls);
      }
      if (fill_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Fill);
      }
      if (stroke_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Stroke);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ClosedVector other) {
      if (other == null) {
        return;
      }
      if (other.closedVectorControls_ != null) {
        if (closedVectorControls_ == null) {
          ClosedVectorControls = new global::DesignModel.ContentTypes.Controls.ClosedVectorControls();
        }
        ClosedVectorControls.MergeFrom(other.ClosedVectorControls);
      }
      if (other.fill_ != null) {
        if (fill_ == null) {
          Fill = new global::DesignModel.AppearanceTypes.Fill();
        }
        Fill.MergeFrom(other.Fill);
      }
      if (other.stroke_ != null) {
        if (stroke_ == null) {
          Stroke = new global::DesignModel.AppearanceTypes.Stroke();
        }
        Stroke.MergeFrom(other.Stroke);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (closedVectorControls_ == null) {
              ClosedVectorControls = new global::DesignModel.ContentTypes.Controls.ClosedVectorControls();
            }
            input.ReadMessage(ClosedVectorControls);
            break;
          }
          case 18: {
            if (fill_ == null) {
              Fill = new global::DesignModel.AppearanceTypes.Fill();
            }
            input.ReadMessage(Fill);
            break;
          }
          case 26: {
            if (stroke_ == null) {
              Stroke = new global::DesignModel.AppearanceTypes.Stroke();
            }
            input.ReadMessage(Stroke);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (closedVectorControls_ == null) {
              ClosedVectorControls = new global::DesignModel.ContentTypes.Controls.ClosedVectorControls();
            }
            input.ReadMessage(ClosedVectorControls);
            break;
          }
          case 18: {
            if (fill_ == null) {
              Fill = new global::DesignModel.AppearanceTypes.Fill();
            }
            input.ReadMessage(Fill);
            break;
          }
          case 26: {
            if (stroke_ == null) {
              Stroke = new global::DesignModel.AppearanceTypes.Stroke();
            }
            input.ReadMessage(Stroke);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
