// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: content/controls/opened_vector_controls.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DesignModel.ContentTypes.Controls {

  /// <summary>Holder for reflection information generated from content/controls/opened_vector_controls.proto</summary>
  public static partial class OpenedVectorControlsReflection {

    #region Descriptor
    /// <summary>File descriptor for content/controls/opened_vector_controls.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OpenedVectorControlsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci1jb250ZW50L2NvbnRyb2xzL29wZW5lZF92ZWN0b3JfY29udHJvbHMucHJv",
            "dG8SF2Rlc2lnbi5jb250ZW50LmNvbnRyb2xzGiRjb250ZW50L2NvbnRyb2xz",
            "L2xpbmVfY29udHJvbHMucHJvdG8aKGNvbnRlbnQvY29udHJvbHMvcG9seWxp",
            "bmVfY29udHJvbHMucHJvdG8aJGNvbnRlbnQvY29udHJvbHMvcGF0aF9jb250",
            "cm9scy5wcm90byL4AQoUT3BlbmVkVmVjdG9yQ29udHJvbHMSPgoNbGluZV9j",
            "b250cm9scxgBIAEoCzIlLmRlc2lnbi5jb250ZW50LmNvbnRyb2xzLkxpbmVD",
            "b250cm9sc0gAEkYKEXBvbHlsaW5lX2NvbnRyb2xzGAIgASgLMikuZGVzaWdu",
            "LmNvbnRlbnQuY29udHJvbHMuUG9seWxpbmVDb250cm9sc0gAEj4KDXBhdGhf",
            "Y29udHJvbHMYAyABKAsyJS5kZXNpZ24uY29udGVudC5jb250cm9scy5QYXRo",
            "Q29udHJvbHNIAEIYChZvcGVuZWRfdmVjdG9yX2NvbnRyb2xzQiSqAiFEZXNp",
            "Z25Nb2RlbC5Db250ZW50VHlwZXMuQ29udHJvbHNiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DesignModel.ContentTypes.Controls.LineControlsReflection.Descriptor, global::DesignModel.ContentTypes.Controls.PolylineControlsReflection.Descriptor, global::DesignModel.ContentTypes.Controls.PathControlsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DesignModel.ContentTypes.Controls.OpenedVectorControls), global::DesignModel.ContentTypes.Controls.OpenedVectorControls.Parser, new[]{ "LineControls", "PolylineControls", "PathControls" }, new[]{ "OpenedVectorControls" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class OpenedVectorControls : pb::IMessage<OpenedVectorControls>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OpenedVectorControls> _parser = new pb::MessageParser<OpenedVectorControls>(() => new OpenedVectorControls());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OpenedVectorControls> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DesignModel.ContentTypes.Controls.OpenedVectorControlsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenedVectorControls() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenedVectorControls(OpenedVectorControls other) : this() {
      switch (other.OpenedVectorControlsCase) {
        case OpenedVectorControlsOneofCase.LineControls:
          LineControls = other.LineControls.Clone();
          break;
        case OpenedVectorControlsOneofCase.PolylineControls:
          PolylineControls = other.PolylineControls.Clone();
          break;
        case OpenedVectorControlsOneofCase.PathControls:
          PathControls = other.PathControls.Clone();
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenedVectorControls Clone() {
      return new OpenedVectorControls(this);
    }

    /// <summary>Field number for the "line_controls" field.</summary>
    public const int LineControlsFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DesignModel.ContentTypes.Controls.LineControls LineControls {
      get { return openedVectorControlsCase_ == OpenedVectorControlsOneofCase.LineControls ? (global::DesignModel.ContentTypes.Controls.LineControls) openedVectorControls_ : null; }
      set {
        openedVectorControls_ = value;
        openedVectorControlsCase_ = value == null ? OpenedVectorControlsOneofCase.None : OpenedVectorControlsOneofCase.LineControls;
      }
    }

    /// <summary>Field number for the "polyline_controls" field.</summary>
    public const int PolylineControlsFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DesignModel.ContentTypes.Controls.PolylineControls PolylineControls {
      get { return openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PolylineControls ? (global::DesignModel.ContentTypes.Controls.PolylineControls) openedVectorControls_ : null; }
      set {
        openedVectorControls_ = value;
        openedVectorControlsCase_ = value == null ? OpenedVectorControlsOneofCase.None : OpenedVectorControlsOneofCase.PolylineControls;
      }
    }

    /// <summary>Field number for the "path_controls" field.</summary>
    public const int PathControlsFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DesignModel.ContentTypes.Controls.PathControls PathControls {
      get { return openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PathControls ? (global::DesignModel.ContentTypes.Controls.PathControls) openedVectorControls_ : null; }
      set {
        openedVectorControls_ = value;
        openedVectorControlsCase_ = value == null ? OpenedVectorControlsOneofCase.None : OpenedVectorControlsOneofCase.PathControls;
      }
    }

    private object openedVectorControls_;
    /// <summary>Enum of possible cases for the "opened_vector_controls" oneof.</summary>
    public enum OpenedVectorControlsOneofCase {
      None = 0,
      LineControls = 1,
      PolylineControls = 2,
      PathControls = 3,
    }
    private OpenedVectorControlsOneofCase openedVectorControlsCase_ = OpenedVectorControlsOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OpenedVectorControlsOneofCase OpenedVectorControlsCase {
      get { return openedVectorControlsCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearOpenedVectorControls() {
      openedVectorControlsCase_ = OpenedVectorControlsOneofCase.None;
      openedVectorControls_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OpenedVectorControls);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OpenedVectorControls other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(LineControls, other.LineControls)) return false;
      if (!object.Equals(PolylineControls, other.PolylineControls)) return false;
      if (!object.Equals(PathControls, other.PathControls)) return false;
      if (OpenedVectorControlsCase != other.OpenedVectorControlsCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.LineControls) hash ^= LineControls.GetHashCode();
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PolylineControls) hash ^= PolylineControls.GetHashCode();
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PathControls) hash ^= PathControls.GetHashCode();
      hash ^= (int) openedVectorControlsCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.LineControls) {
        output.WriteRawTag(10);
        output.WriteMessage(LineControls);
      }
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PolylineControls) {
        output.WriteRawTag(18);
        output.WriteMessage(PolylineControls);
      }
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PathControls) {
        output.WriteRawTag(26);
        output.WriteMessage(PathControls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.LineControls) {
        output.WriteRawTag(10);
        output.WriteMessage(LineControls);
      }
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PolylineControls) {
        output.WriteRawTag(18);
        output.WriteMessage(PolylineControls);
      }
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PathControls) {
        output.WriteRawTag(26);
        output.WriteMessage(PathControls);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.LineControls) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LineControls);
      }
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PolylineControls) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PolylineControls);
      }
      if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PathControls) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PathControls);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OpenedVectorControls other) {
      if (other == null) {
        return;
      }
      switch (other.OpenedVectorControlsCase) {
        case OpenedVectorControlsOneofCase.LineControls:
          if (LineControls == null) {
            LineControls = new global::DesignModel.ContentTypes.Controls.LineControls();
          }
          LineControls.MergeFrom(other.LineControls);
          break;
        case OpenedVectorControlsOneofCase.PolylineControls:
          if (PolylineControls == null) {
            PolylineControls = new global::DesignModel.ContentTypes.Controls.PolylineControls();
          }
          PolylineControls.MergeFrom(other.PolylineControls);
          break;
        case OpenedVectorControlsOneofCase.PathControls:
          if (PathControls == null) {
            PathControls = new global::DesignModel.ContentTypes.Controls.PathControls();
          }
          PathControls.MergeFrom(other.PathControls);
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            global::DesignModel.ContentTypes.Controls.LineControls subBuilder = new global::DesignModel.ContentTypes.Controls.LineControls();
            if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.LineControls) {
              subBuilder.MergeFrom(LineControls);
            }
            input.ReadMessage(subBuilder);
            LineControls = subBuilder;
            break;
          }
          case 18: {
            global::DesignModel.ContentTypes.Controls.PolylineControls subBuilder = new global::DesignModel.ContentTypes.Controls.PolylineControls();
            if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PolylineControls) {
              subBuilder.MergeFrom(PolylineControls);
            }
            input.ReadMessage(subBuilder);
            PolylineControls = subBuilder;
            break;
          }
          case 26: {
            global::DesignModel.ContentTypes.Controls.PathControls subBuilder = new global::DesignModel.ContentTypes.Controls.PathControls();
            if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PathControls) {
              subBuilder.MergeFrom(PathControls);
            }
            input.ReadMessage(subBuilder);
            PathControls = subBuilder;
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            global::DesignModel.ContentTypes.Controls.LineControls subBuilder = new global::DesignModel.ContentTypes.Controls.LineControls();
            if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.LineControls) {
              subBuilder.MergeFrom(LineControls);
            }
            input.ReadMessage(subBuilder);
            LineControls = subBuilder;
            break;
          }
          case 18: {
            global::DesignModel.ContentTypes.Controls.PolylineControls subBuilder = new global::DesignModel.ContentTypes.Controls.PolylineControls();
            if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PolylineControls) {
              subBuilder.MergeFrom(PolylineControls);
            }
            input.ReadMessage(subBuilder);
            PolylineControls = subBuilder;
            break;
          }
          case 26: {
            global::DesignModel.ContentTypes.Controls.PathControls subBuilder = new global::DesignModel.ContentTypes.Controls.PathControls();
            if (openedVectorControlsCase_ == OpenedVectorControlsOneofCase.PathControls) {
              subBuilder.MergeFrom(PathControls);
            }
            input.ReadMessage(subBuilder);
            PathControls = subBuilder;
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
